apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-flask-app.fullname" . }}
  labels:
    {{- include "my-flask-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "my-flask-app.name" . }}
