replicaCount: 1

image:
  repository: yeshwanthan/my-flask-app
  tag: latest

service:
  name: my-flask-app
  type: NodePort
  port: 80
  nodePort: 30001

imagePullSecrets:
  - name: regcred

ingress:
  enabled: false
  name: ""

resources: {}
